### ISSUE TITLE
MBTiles - metadata - suggestion for OpenStreetMap support

### ISSUE THREAD

**Issue by mj10777** [mapbox/mbtiles-spec#35]
In the 'Roadmap' text it is suggesting that support for the OpenStreetMap  naming convention is being considered.

https://github.com/mapbox/mbtiles-spec/

'The format will switch tile ordering to the XYZ schema popularized by OpenStreetMap and away from the Tile Map Service specification.'

I would like to suggest the following:

add a 'metadata' name:
name='tile_row_type'

with (at the moment) 2 possible values:

'tms'
'osm'

A reader could then check for 'tile_row_type':
- if not found OR 'tms'
-- assume 'Tile Map Service Specification' as described at
http://wiki.osgeo.org/wiki/Tile_Map_Service_Specification
- if 'osm' is found
-- assume 'Slippy map tilenames' as described at
http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames

I am the author of the Bash-Shell script tileinfo.sh

http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#tileinfo.sh

this tool was developed as a helper to determine a tile address from a WSG84-position (for both tms and osm)
or to determine a WSG84-position from a tile address (for both tms and osm).

Today I have added the functionality of creating a .mbtile database from an existing tile-directory
- assuming that either sqlite3 or spatialite is installed
- a parameter can be given to tell the script that the tile-directory is a tms directory

Here I have added the metadata name 'tile_row_type', setting the value always to 'tms' - since all readers (at the moment) assume this. I will be doing the same for a QT based map library that reads tile-directorys and show the result on a map.

There are also Android applications, that together with their format (similar, yet different) also can read the present mbtiles format.
- OruxMaps is the Application that I use mostly on my telefon/tablet and this application can read the created .mbtiles
-- including the metadata names bounds and center - when listed: shows the extent of 'bounds' and when opened zooms to the position given in 'center'
-- unfortunately, at the moment at least, a empty 'android_metadata' table must exist for this to work
I have had contact with this developer and would like to convince him to switch over to the .mbtiles format.
At the moment his application can create and fill a sqlite.db from an selected area.
The created database uses the fields (z,x,y,image) and stores a 'CalibrationPoint' in an external xml file, which is used as the (oms) position 0,0.
I am planing to work on a conversion function for this and will be using a 'calibration_point' in the metadata to calculate the offset from the default value of: '-180,-85.0511,180,85.0511'

For this reason I would also suggest adding a name 'calibration_point'
- the default being  '-180,-85.0511,180,85.0511'.

Adding these 2 values for reading applications to use would, I believe, encourage a wider use of the .mbtiles format.

Mark Johnson, Berlin Germany

**Comment by tmcw** [comment]
Closing; this behavior is documented and should be implemented as in the spec.
