### ISSUE TITLE
Regarding .MBTiles to .DB Conversion

### ISSUE THREAD

**Issue by sakibnaz** [mapbox/mbtiles-spec#42]
Hi.

I am using an Android Apps for Offline Mapping that uses .DB file for Map SQLite Database. I am trying to view my own Country Map by making .MBTiles using TileMill then rename the .MBTiles to .DB.

I observed the Map is not coming to the Apps. After doing several Zoom-out I can see the Map. Still while Zoom-In the Map the area gets divided into two Parts.

So far I think the problem is due to MBTiles Inverted Y-Axis. Please correct me if my thought is wrong.

I wanted to ask ... Is there any way to export OSM Data as .DB (not .MBTiles) by setting Min and Max Zoom level and Boundary?

Or any way to convert .MBTiles to .DB?

Thanks in advance.

Regards.

**Comment by tmcw** [comment]
Can you be more specific about _which_ `.DB` file format you're referring to?

**Comment by sakibnaz** [comment]
Hi TMCW.

I mean ... SQLite .DB file for OSM Map.

I am trying to use the below Android App:

http://tech-blog.silviaterra.com/2014/05/offline-mapping-with-phonegap-build-and.html

Apologies if still my answer did not clarify well. I am very new in GIS.

Thanks.

Regards.

**Comment by tmcw** [comment]
Closing; sorry, this is very specific to an unstandardized other format.
