### ISSUE TITLE
zxy from zoom_level, tile_column, tile_row in mbtiles file

### ISSUE THREAD

**Issue by divya1c** [mapbox/mbtiles-spec#48]
Hi! 

I want to get all the zxy of tiles present. So, I opened my mbtiles file in an sqlite3 viewer. I see that my zoom_level and tile_column values are the same as z and x in my mapbox-gl front end requests. But, my tile_row is very different from my y. How do I get my y from the tile_row?  

Thanks :)

**Comment by divya1c** [comment]
I found the answer in tippecanoe's readme. I'm using tippecanoe-enumerate to list all tiles.

**Comment by ericfischer** [comment]
You can also get the ZXY-style y coordinate with

```
select zoom_level, tile_column, (1 << zoom_level) - 1 - tile_row from tiles;
```
