### ISSUE TITLE
Uncaught (in promise) Error: Unimplemented type: 3

### ISSUE THREAD

**Issue by brstillwell** [mapbox/mbtiles-spec#52]
I have read that this error is being caused by the pbf files not being gzipped when being imported and saved. How exactly do I compress them in transit? I have installed the compression module for express and I gzips everything except these pbfs. Is there some sort of middleware that I am missing?

**Comment by pnorman** [comment]
> I have read that this error is being caused by the pbf files not being gzipped when being imported and saved. How exactly do I compress them in transit? I have installed the compression module for express and I gzips everything except these pbfs. Is there some sort of middleware that I am missing?

You've opened this issue against the mbtiles specification, not any software. You probably want to open an issue there.

As for vector tiles, the spec currently does not allow storing them in mbtiles, so you'll have to look at what the software you're using expects for compression, formats, etc for their own mbtiles-like format.

**Comment by brstillwell** [comment]
Thank you for letting me know. I will close this issue.
